version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  
  pre-build:
    commands:
        - echo "Pre build commands....."
        - echo "aws cli verion: `aws --version`"
  
  build:
    commands:
      - echo "Starting maven build on `date`"
      - mvn -B verify --file pom.xml
      - echo "Completed maven build successfully!"
      
  post-build:
    commands:
       - echo "Creating Docker image