version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  
  pre_build:
    commands:
        - echo Pre build starts at `date`
        - aws --version
        - echo "Region: $AWS_DEFAULT_REGION, Account: $AWS_ACCOUNT_ID"
        - echo "Docker tag: $IMAGE_REPO_NAME:$IMAGE_TAG"
  
  build:
    commands:
      - echo "Starting maven build on `date`"
      - mvn -B verify --file pom.xml
      - echo "Completed maven build successfully!"
      
  post_build:
    commands:
       - echo Creating Docker image